# Generated by Django 5.0.7 on 2024-12-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0003_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsmessage',
            name='age',
        ),
        migrations.RemoveField(
            model_name='visitorsmessage',
            name='image',
        ),
    ]
