# Generated by Django 5.0.7 on 2024-12-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_app', '0007_alter_product_image_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(help_text="Enter quantity with units like '10kgs' or '500g'.", max_length=20),
        ),
    ]
